# Generated by Django 4.2 on 2025-10-02 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(help_text="Duration in minutes"),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("HR", "HR/Admin"), ("Candidate", "Candidate")],
                        max_length=10,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[("MCQ", "Multiple Choice"), ("DESC", "Descriptive")],
                        max_length=10,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="commonapp.assessment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_text", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="commonapp.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CandidateAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commonapp.assessment",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        limit_choices_to={"userprofile__role": "Candidate"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CandidateAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descriptive_answer", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "candidate_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commonapp.candidateassessment",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commonapp.question",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="commonapp.option",
                    ),
                ),
            ],
        ),
    ]
