# Generated by Django 4.2 on 2025-10-03 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("commonapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("HR", "HR"), ("Admin", "Admin"), ("Candidate", "Candidate")],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="TypeLookup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datafield", models.CharField(max_length=255)),
                ("datafor", models.CharField(max_length=255)),
                ("dataparamtext", models.CharField(max_length=255)),
                ("dataparamvalue", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "modified_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_lookup",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
