# Generated by Django 4.2 on 2025-10-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commonapp", "0002_alter_userprofile_role_typelookup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="modified_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="candidateanswer",
            name="modified_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="candidateassessment",
            name="modified_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="option",
            name="modified_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="modified_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="typelookup",
            name="modified_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="modified_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
