# Generated by Django 4.2 on 2025-10-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commonapp", "0003_alter_assessment_modified_datetime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="language",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="site",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
