# Generated by Django 4.2 on 2025-10-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commonapp", "0004_userprofile_language_userprofile_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="candpassword",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
