# Generated by Django 5.2.7 on 2025-11-11 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commonapp", "0008_alter_assessment_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="typelookup",
            name="created_by",
            field=models.ForeignKey(
                db_column="created_by_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="AssessmentConduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(blank=True, null=True)),
                ("assessment_date", models.DateField()),
                (
                    "assessment_start_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "assessment_end_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "type_of_closure",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("timeout", "Timeout"),
                            ("user_end", "User Ended"),
                            ("auto_close", "Auto Closed"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducts",
                        to="commonapp.assessment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="modified_by_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessment_conducts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment Conduct",
                "verbose_name_plural": "Assessment Conducts",
                "ordering": ["-assessment_date"],
            },
        ),
    ]
