# Generated by Django 5.2.7 on 2025-11-12 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("commonapp", "0009_alter_typelookup_created_by_assessmentconduct"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AssessmentConduct",
        ),
    ]
