# Generated by Django 5.2.7 on 2025-11-13 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commonapp", "0011_assessmentconduct"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidateanswer",
            name="candidate_assessment",
        ),
        migrations.RemoveField(
            model_name="candidateanswer",
            name="descriptive_answer",
        ),
        migrations.AddField(
            model_name="candidateanswer",
            name="assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidate_answers",
                to="commonapp.assessment",
            ),
        ),
        migrations.AddField(
            model_name="candidateanswer",
            name="assessmentconduct",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidate_answers",
                to="commonapp.assessmentconduct",
            ),
        ),
        migrations.AddField(
            model_name="candidateanswer",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidate_answers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="candidateanswer",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="candidateanswer",
            name="score",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="candidateanswer",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidate_answers",
                to="commonapp.question",
            ),
        ),
        migrations.AlterField(
            model_name="candidateanswer",
            name="selected_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidate_answers",
                to="commonapp.option",
            ),
        ),
        migrations.DeleteModel(
            name="CandidateAssessment",
        ),
    ]
