# Generated by Django 5.2.7 on 2025-11-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commonapp", "0012_remove_candidateanswer_candidate_assessment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateanswer",
            name="question_status",
            field=models.CharField(
                blank=True,
                choices=[("viewed", "Viewed"), ("answered", "Answered")],
                max_length=10,
                null=True,
            ),
        ),
    ]
