# Generated by Django 5.2.7 on 2025-11-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commonapp", "0013_candidateanswer_question_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateanswer",
            name="question_status",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
