# Generated by Django 5.2.7 on 2025-11-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commonapp", "0014_alter_candidateanswer_question_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentconduct",
            name="duration",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
