# Generated by Django 5.2.11 on 2026-02-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commonapp", "0015_alter_assessmentconduct_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("Admin", "Admin"), ("Candidate", "Candidate")], max_length=10
            ),
        ),
    ]
