# Generated by Django 5.2.11 on 2026-02-05 12:50

from django.db import migrations

import apps.assessment_api.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", apps.assessment_api.managers.UserManager()),
            ],
        ),
    ]
